// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn2xbmCCi9AFV8U6Xs-tu7h96GiIdYGxM',
    appId: '1:1060838827175:web:b74f82ef67ca987c316782',
    messagingSenderId: '1060838827175',
    projectId: 'paywsir',
    authDomain: 'paywsir.firebaseapp.com',
    storageBucket: 'paywsir.appspot.com',
    measurementId: 'G-QVK0V7M0ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCflbf6YAT9t2ZaoB8VjTto5njMQFzzTrk',
    appId: '1:1060838827175:android:21c8ad09ee747c7c316782',
    messagingSenderId: '1060838827175',
    projectId: 'paywsir',
    storageBucket: 'paywsir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVHkBK41nX7N-qrJiOT5FBx1_uQlyJOtE',
    appId: '1:1060838827175:ios:45467922238f86f3316782',
    messagingSenderId: '1060838827175',
    projectId: 'paywsir',
    storageBucket: 'paywsir.appspot.com',
    iosBundleId: 'com.example.paywsir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVHkBK41nX7N-qrJiOT5FBx1_uQlyJOtE',
    appId: '1:1060838827175:ios:3d9b87d0b1ecfb76316782',
    messagingSenderId: '1060838827175',
    projectId: 'paywsir',
    storageBucket: 'paywsir.appspot.com',
    iosBundleId: 'com.example.paywsir.RunnerTests',
  );
}
